version: 2
builds:
  - main: ./cmd/ssh-to-age
    binary: ssh-to-age
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: [binary]
    name_template: "{{ .Binary }}.{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "sha256sums.txt"

release:
  draft: false
